devices:
  - name: hichi
    type: json
    topic: tele/tasmota_FA2296/SENSOR
    only_match: 1_8_0
    mappings:
      - 1_8_0: Total consumption
      - 1_8_1: Tariff 1 consumption 
      - 1_8_2: Tariff 1 delivered
      - 2_8_0: Energy export
      - 16_7_0: Current usage
      - 36_7_0: Current usage phase 1
      - 56_7_0: Current usage phase 2
      - 76_7_0: Current usage phase 3
      - 96_1_0: Device ID
  - name: tele (parents Jens)
    type: json
    topic: tele/power/SENSOR
    mappings:
      - Total_in: Sum received
      - Total_out: Sum delivered
      - Power_curr: Current usage
